swagger: "2.0"
info:
  description: "TBD"
  version: "1.1.1"
  title: "FORGE playground example 1"
  termsOfService: "http://www.etsi.org/terms-of-use"
paths:
  /standard:
    get:
      summary: "Query Standards"
      description: ""
      operationId: "queryStandards"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Standards request object"
        schema:
          $ref: "#/definitions/StandardRequest"
      responses:
        200:
          description: "The list of standards was retrieved correctly."
          schema:
            type: array
            items:
              $ref: '#/definitions/Standard'
        401:
          description: "Invalid input"
        404:
            description: "Not found"
    post:
      summary: Upload a new standard
      description: Use this to create a new ref to a standard
      parameters:
 '
    
definitions:
  Standard:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        example: "ETSI EN 302 636-4-1"
      url:
        type: "str