swagger: "2.0"
info:
  description: "TBD"
  version: "1.1.1"
  title: "FORGE playground example 1"
  termsOfService: "http://www.etsi.org/terms-of-use"
  contact:
    email: "cti_support@etsi.org"
  license:
    name: "ETSI"
    url: "http://www.etsi.org/terms-of-use"
host: "forge.etsi.org"
basePath: "/v1"
schemes:
- "http"
paths:
  /standard:
    get:
      summary: "Query Standards"
      description: ""
      operationId: "queryStandards"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Standards request object"
        schema:
          $ref: "#/definitions/StandardRequest"
      responses:
        TESTING VALIDATION OF OPENAPIS TEST. ASP
        405:
          description: "Invalid input"
        404:
            description: "not found"
definitions:
  Standard:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        example: "ETSI EN 302 636-4-1"
      url:
        type: "string"
        xml:
          name: "url"
          wrapped: true
      status:
        type: "string"
        description: "Status of the standard"
        enum:
        - "Draft"
        - "Approval"
        - "Published"
    xml:
      name: "Standard"
  StandardRequest:
    type: "object"
    required:
    - "keyword"
    properties:
      keyword:
        type: "string"
        example: "ITS"
externalDocs:
  description: "Find out more about ETSI Forge"
  url: "http://etsi.org"
